global:
    nside: 2048
    sparse: True
    pixelization: healpix
    chunk_rows:  100000
    true_shear: True


TXSourceSelector:
    input_pz: False
    bands: riz
    T_cut: 0.5
    s2n_cut: 10.
    max_rows: 1000
    delta_gamma: 0.02
    # 7 bins
    source_zbin_edges: [0.19285902, 0.40831394, 0.65503818, 0.94499109, 1.2947086, 1.72779632, 2.27855242, 3.]
    true_z: False
    shear_prefix: mcal_


TXShearCalibration:
    use_true_shear: True
    subtract_mean_shear: False

TXLensCatalogSplitter: {}


TXSourceMaps: {}


TXAuxiliaryMaps:
    psf_prefix:  psf_
    bright_obj_threshold:  22.0


TXSimpleMask:
    depth_cut: 23.0
    bright_object_max: 10.0        


TXSourceTrueNumberDensity:
    nz: 301
    zmax: 3.0


TXIngestRedmagic:
    lens_zbin_edges: [0.15, 0.3, 0.45, 0.6, 0.75, 0.9]

TXPhotozPlots: {}

TXTracerMetadata: {}

TXRandomCat:
    density: 10 # gals per sq arcmin

TXJackknifeCenters:
    npatch: 40


TXTwoPointLensCat:
    bin_slop: 0.0
    delta_gamma: 0.02
    do_pos_pos: True
    do_shear_shear: True
    do_shear_pos: True
    flip_g2: True  # use true when using metacal shears
    min_sep: 2.5
    max_sep: 100
    nbins: 15
    verbose: 0
    use_true_shear: True
    subtract_mean_shear: True
    var_method: jackknife

TXNullBlinding: {}

TXRealGaussianCovariance:
    min_sep: 2.5
    max_sep: 100.
    nbins: 15
    use_true_shear: True



TXTwoPointTheoryReal: {}

TXTwoPointPlots: {}