TXGCRTwoCatalogInput:
    metacal_dir: /global/cscratch1/sd/desc/DC2/data/Run2.2i/dpdd/Run2.2i-t3828/metacal_table_summary
    photo_dir: /global/cscratch1/sd/desc/DC2/data/Run2.2i/dpdd/Run2.2i-t3828/object_table_summary

TXMetacalGCRInput:
    cat_name: dc2_object_run2.1i_dr1b_with_metacal_griz

TXExposureInfo:
    dc2_name: '1.2p'


TXCosmoDC2Mock:
    cat_name: cosmoDC2_v1.1.4_image
    visits_per_band: 16
    extra_cols: redshift_true size_true shear_1 shear_2 Mag_true_r_sdss_z0 
    flip_g2: True # to match metacal
    snr_limit: 4.0
    Mag_r_limit: -19
    unit_response: True
    apply_mag_cut: False

TXIngestRedmagic:
    lens_zbin_edges: [0.15, 0.3, 0.45, 0.6, 0.75, 0.9]

TXSourceTrueNumberDensity:
    nz: 601
    zmax: 3.0
    chunk_rows: 100000

TXShearCalibration:
    use_true_shear: True
    subtract_mean_shear: True

TXMainMaps:
    chunk_rows:  100000
    pixelization: healpix
    nside: 2048
    sparse: True

TXSourceMaps:
    nside: 2048
    sparse: True
    chunk_rows:  100000
    pixelization: healpix
    true_shear: True

TXExternalLensMaps:
    nside: 2048
    sparse: True
    chunk_rows:  100000
    pixelization: healpix

TXAuxiliarySourceMaps:
    chunk_rows:  100000
    sparse:  True
    psf_prefix:  psf_

TXAuxiliaryLensMaps:
    chunk_rows:  100000
    sparse:  True
    bright_obj_threshold:  22.0

TXSimpleMask:
    depth_cut: 23.0
    bright_object_max: 10.0        


PZPDFMLZ:
    nz: 301
    zmax: 3.0
    chunk_rows: 100000

TXPhotozStack:
    chunk_rows: 100000

# Mock version of stacking:
TXTrueNumberDensity:
    nz: 301
    zmax: 3.0
    chunk_rows: 100000

TXSourceSelector:
    input_pz: False
    bands: riz #used for selection
    T_cut: 0.5
    s2n_cut: 10.
    max_rows: 1000
    delta_gamma: 0.02
    # source_zbin_edges: [0.25588604, 0.55455363, 0.91863365, 1.38232001, 2.]
    source_zbin_edges: [0.19285902, 0.40831394, 0.65503818, 0.94499109, 1.2947086, 1.72779632, 2.27855242, 3. ] # 7 bins
    chunk_rows: 100000
    true_z: False
    shear_prefix: mcal_

TXRandomCat:
    chunk_rows: 100000
    density: 10 # gals per sq arcmin

TXJackknifeCenters:
    npatch: 40

TXDiagnosticPlots:
    shear_prefix: mcal_

TXFourierGaussianCovariance:
    use_true_shear: True

TXRealGaussianCovariance:
    min_sep: 2.5
    max_sep: 100.
    nbins: 15
    use_true_shear: True

TXTwoPoint:
    bin_slop: 0.0
    delta_gamma: 0.02
    do_pos_pos: True
    do_shear_shear: True
    do_shear_pos: True
    flip_g2: True  # use true when using metacal shears
    min_sep: 2.5
    max_sep: 100
    nbins: 15
    verbose: 0
    var_method: jackknife

TXTwoPointFourier:
    chunk_rows: 100000
    flip_g2: True
    flip_g1: True
    apodization_size: 0.0
    cache_dir: ./cache
    true_shear: True
    n_ell: 20
    ell_max: 3000
    nside: 2048

TXClusteringNoiseMaps:
    n_realization: 30

TXLensingNoiseMaps:
    n_realization: 30

TXTruthLensSelector:
    # Mag cuts
    chunk_rows: 100000
    lens_zbin_edges: [0.0,0.2,0.4]
    cperp_cut: 0.2
    r_cpar_cut: 13.5
    r_lo_cut: 16.0
    r_hi_cut: 21.6
    i_lo_cut: 17.5
    i_hi_cut: 21.9
    r_i_cut: 2.0
