global:
    chunk_rows: 100000
    sparse: True  # Generate sparse maps - faster if using small areas
    pixelization: healpix
    nside: 512

TXGCRTwoCatalogInput:
    metacal_dir: /global/cscratch1/sd/desc/DC2/data/Run2.2i/dpdd/Run2.2i-t3828/metacal_table_summary
    photo_dir: /global/cscratch1/sd/desc/DC2/data/Run2.2i/dpdd/Run2.2i-t3828/object_table_summary

TXMetacalGCRInput:
    cat_name: dc2_object_run2.1i_dr1b_with_metacal_griz

TXExposureInfo:
    dc2_name: '1.2p'


TXCosmoDC2Mock:
    cat_name: cosmoDC2_v1.1.4_image
    visits_per_band: 16
    extra_cols: redshift_true size_true shear_1 shear_2
    flip_g2: True # to match metacal


PZPDFMLZ:
    nz: 301
    zmax: 3.0



PZRailTrainLens:
    class_name: BPZ_lite
    zmin: 0.0
    zmax: 2.0
    dz: 0.01
    columns_file: ./examples/config/bpz_ugrizy.columns
    spectra_file: SED/CWWSB4.list
    prior_band: i
    # Not sure about this
    prior_file: hdfn_gen
    p_min: 0.005
    gauss_kernel: 0.0
    mag_err_min: 0.005
    inform_options: {'save_train': False, 'load_model': False, 'modelfile': 'BPZpriormodel.out'}  
    madau_reddening: no
    bands: ugrizy
    zp_errors: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]

PZRailEstimateLens:
    convert_unseen: True
    bands: ugrizy


TXPhotozStack: {}

# Mock version of stacking:
TXTrueNumberDensity:
    nz: 301
    zmax: 3.0

TXSourceSelector:
    input_pz: True
    bands: ri #used for selection
    T_cut: 0.25
    s2n_cut: 5.0
    max_rows: 1000
    delta_gamma: 0.02
    source_zbin_edges: [0.1, 0.5, 1.0, 2.0]
    shear_prefix: ''
    input_m_is_weighted: True

TXTruthLensSelector:
    # Mag cuts
    lens_zbin_edges: [0.0,0.2,0.4]
    cperp_cut: 0.2
    r_cpar_cut: 13.5
    r_lo_cut: 16.0
    r_hi_cut: 21.6
    i_lo_cut: 17.5
    i_hi_cut: 21.9
    r_i_cut: 2.0
    # may also need one for r_cpar_cut

TXMeanLensSelector:
    # Mag cuts
    lens_zbin_edges: [0.0,0.2,0.4]
    cperp_cut: 0.2
    r_cpar_cut: 13.5
    r_lo_cut: 16.0
    r_hi_cut: 21.6
    i_lo_cut: 17.5
    i_hi_cut: 21.9
    r_i_cut: 2.0

TXRandomCat:
    density: 10 # gals per sq arcmin

TXTwoPoint:
    bin_slop: 0.1
    delta_gamma: 0.02
    do_pos_pos: True
    do_shear_shear: True
    do_shear_pos: True
    flip_g2: True  # use true when using metacal shears
    min_sep: 2.5
    max_sep: 60.0
    nbins: 10
    verbose: 0
    shear_catalog_type: metacal
    subtract_mean_shear: True

TXGammaTBrightStars:
    shear_catalog_type: metacal

TXGammaTDimStars:
    shear_catalog_type: metacal

TXGammaTFieldCenters:
    shear_catalog_type: metacal

TXBlinding:
    seed: 1972  ## seed uniquely specifies the shift in parameters
    Omega_b: [0.0485, 0.001] ## fiducial_model_value, shift_sigma
    Omega_c: [0.2545, 0.01]
    w0: [-1.0, 0.1]
    h: [0.682, 0.02]
    sigma8: [0.801, 0.01]
    n_s: [0.971, 0.03]
    b0: 0.95  ## we use bias of the form b0/g
    delete_unblinded: True

TXDiagnosticPlots:
    psf_prefix: psf_
    shear_prefix: ''
    T_min: 0.5
    T_max: 1.0

TXMapPlots:
    projection: moll

TXDiagnosticMaps:
    sparse: True  # Generate sparse maps - faster if using small areas
    snr_threshold: 10.0
    snr_delta: 1.0
    pixelization: healpix
    nside: 512
    # pixelization: gnomonic
    pixel_size: 0.2
    ra_cent: 62.
    dec_cent: -35.
    npix_x: 60
    npix_y: 60
    depth_cut: 21.5
    psf_prefix: mcal_psf_

TXSourceMaps: {}

TXLensMaps: {}

TXMainMaps: {}

TXAuxiliaryMaps:
    flag_exponent_max: 1
    dilate: True
    psf_prefix: psf_
    bright_obj_threshold: 22.0 # The magnitude threshold for a object to be counted as bright
    depth_band : i
    snr_threshold: 10.0  # The S/N value to generate maps for (e.g. 5 for 5-sigma depth)
    snr_delta: 1.0  # The range threshold +/- delta is used for finding objects at the boundary


TXRealGaussianCovariance:
    min_sep: 2.5
    max_sep: 60.
    nbins: 10
    pickled_wigner_transform: data/example/inputs/wigner.pkl


TXJackknifeCenters:
    npatch: 5


TXTwoPointFourier:
    flip_g2: True
    bandwidth: 100

TXSimpleMask:
    depth_cut : 21.5
    bright_object_max: 10.0
