global:
    chunk_rows: 1000000

TXGCRTwoCatalogInput:
    metacal_dir: /global/cscratch1/sd/desc/DC2/data/Run2.2i/dpdd/Run2.2i-t3828/metacal_table_summary
    photo_dir: /global/cscratch1/sd/desc/DC2/data/Run2.2i/dpdd/Run2.2i-t3828/object_table_summary

TXMetacalGCRInput:
    cat_name: dc2_object_run2.1i_dr1b_with_metacal_griz

TXExposureInfo:
    dc2_name: '1.2p'


TXCosmoDC2Mock:
    cat_name: cosmoDC2_v1.1.4_image
    visits_per_band: 16
    extra_cols: redshift_true size_true shear_1 shear_2
    flip_g2: True # to match metacal

TXIngestRedmagic:
    lens_zbin_edges: [0.1, 0.3, 0.5, 0.7, 0.9]

TXSourceTrueNumberDensity:
    nz: 301
    zmax: 3.0

TXMainMaps:
    pixelization: healpix
    nside: 512
    sparse: True

TXSourceMaps:
    nside: 512
    sparse: True
    pixelization: healpix
    true_shear: False

TXExternalLensMaps:
    nside: 512
    sparse: True
    pixelization: healpix


TXAuxiliarySourceMaps:
    sparse:  True
    psf_prefix:  psf_

TXAuxiliaryLensMaps:
    sparse:  True
    bright_obj_threshold:  22.0

TXSimpleMask:
    depth_cut: 23.0
    bright_object_max: 10.0        


PZPDFMLZ:
    nz: 301
    zmax: 3.0

TXPhotozStack:

# Mock version of stacking:
TXTrueNumberDensity:
    nz: 301
    zmax: 3.0

TXSourceSelector:
    input_pz: False
    bands: riz #used for selection
    T_cut: 0.5
    s2n_cut: 10.0
    max_rows: 1000
    delta_gamma: 0.02
    source_zbin_edges: [0.3, 0.55, 0.8, 1.05, 2.0]
    # may also need one for r_cpar_cut
    true_z: False
    shear_prefix: mcal_

TXRandomCat:
    density: 10 # gals per sq arcmin

TXJackknifeCenters:
    npatch: 40

TXSourceDiagnosticPlots:
    shear_prefix: mcal_

TXRealGaussianCovariance:
    min_sep: 2.5
    max_sep: 250.
    nbins: 20

TXTwoPoint:
    bin_slop: 0.0
    delta_gamma: 0.02
    do_pos_pos: True
    do_shear_shear: True
    do_shear_pos: True
    flip_g2: True  # use true when using metacal shears
    min_sep: 2.5
    max_sep: 250
    nbins: 20
    verbose: 0
    use_true_shear: False

TXTwoPointLensCat:
    bin_slop: 0.0
    delta_gamma: 0.02
    do_pos_pos: True
    do_shear_shear: True
    do_shear_pos: True
    flip_g2: True  # use true when using metacal shears
    min_sep: 2.5
    max_sep: 250
    nbins: 20
    verbose: 0
    use_true_shear: False
    
TXTwoPointFourier:
    flip_g2: True
    flip_g1: True
    apodization_size: 0.0
    cache_dir: ./cache
    true_shear: False
    
TXRealGaussianCovariance:
    use_true_shear: False

TXClusteringNoiseMaps:
    n_realization: 30

TXLensingNoiseMaps:
    n_realization: 30

TXTruthLensSelector:
    # Mag cuts
    lens_zbin_edges: [0.0,0.2,0.4]
    cperp_cut: 0.2
    r_cpar_cut: 13.5
    r_lo_cut: 16.0
    r_hi_cut: 21.6
    i_lo_cut: 17.5
    i_hi_cut: 21.9
    r_i_cut: 2.0
